# Site setings
name: 'AgileObjects'
description: 'Practical, Pragmatic Agile'
logo:
# Author image is used in site sidebar
author:
  name: Steve Wilkes
  image: https://avatars1.githubusercontent.com/u/8459425?s=52&v=4
favicon: 'assets/images/favicon.png'
baseurl: 
post_images_dir: '/assets/images/posts/'
future: true
production_url: https://agileobjects.co.uk
# Add your GA Tracking Id
ga_analytics: UA-165403546-1

# Comment settings
comments:
  enabled: true
  show_count: true
  empty: []
  form_action: 'https://agileobjects-postblogcomment.azurewebsites.net/api/PostBlogComment?code=4M3vF5qIkyTCwtOWjvjJzuPWm7DAyKNxhMLLlj2gaFFHSyLUYQRK5A=='
#  form_action: 'http://localhost:7071/api/PostBlogComment'

# Contact form settings
contact:
  recaptcha_key: '6LctXKYZAAAAAF7Bm_IchT8ZJaqohVK7w-xrPZqy'
  form_action: 'https://agileobjects-email-fa.azurewebsites.net/api/SendEmail?code=9LCTUmc_n3g8jDIuvzrwfzZa4oJ-t1dMDUgPhIWSnxn8AzFuM-9Zzg=='
# form_action: 'http://localhost:7071/api/SendEmail'

# Social links
github: 'agileobjects'
linkedin: 'agileobjects'
stackoverflow: users/721236/steve-wilkes
rss: agileobjects
contact_icon: true

# Products
ao_github: 'https://github.com/agileobjects/agileobjects.github.io'
am_nuget: 'https://www.nuget.org/packages/AgileObjects.AgileMapper'
am_github: 'https://github.com/agileobjects/AgileMapper'
am_docs: 'https://agilemapper.readthedocs.io'
re_nuget: 'https://www.nuget.org/packages/AgileObjects.ReadableExpressions'
re_viz: 'https://marketplace.visualstudio.com/items?itemName=vs-publisher-1232914.ReadableExpressionsVisualizers'
re_github: 'https://github.com/agileobjects/ReadableExpressions'
em_github: 'https://github.com/agileobjects/AgileObjects.Functions.Email'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Products
    url: /products
  - text: Search
    url: /search
  - text: Contact
    url: /contact

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Exclude these files from the production _site
exclude:
  - /.vs
  - /.git
  - /bin
  - /obj
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - .gitignore
  - '*.csproj'
  - bundleconfig.json